### PR TITLE
Allow relative imports

### PR DESCRIPTION
**Pull request by MarcoThePoro**
Currently `@import` only works relative to the project root or paths statically specified in `includePaths` in the plugin options.

These changes should allow files to specify imports relative to their own directory, given the `filename` field is provided to the plugin.

Currently the `filename` field is only provided in limited cases (or not at all as I wasn't able to produce a case where it was), but I have an open pull request to styled-jsx which should make `filename` present in most cases: https://github.com/zeit/styled-jsx/pull/375

Should fix https://github.com/giuseppeg/styled-jsx-plugin-sass/issues/10

Any feedback is appreciated and thanks!

### CODE REVIEW

**Comment by kylehotchkiss** [comment]
I’m just trying out styled-jsx with sass and could use this fix myself.

**Comment by keegan-lillo** [comment]
Bumping this because it would be really handy for my team.

**Comment by obedparla** [comment]
+1 to this

**Comment by giuseppeg** [comment]
sorry for the delay, published this as v`0.2.3`

**Comment by littlepoolshark** [comment]
Thanks a lot , it is really handy for my team.@MarcoThePoro

**Comment by claudijo** [comment]
Since this fix was reverted in version 1... Is there a way to resolve relative @import paths when using sass with styled jsx ?

**Pull request merged**
